export const terminalLines = [
  {
    path: '~/Jon/Skills',
    input: 'ls',
    results: [
      'React',
      'TypeScript',
      'Go',
      'Turborepo',
      'Bazel',
      'JavaScript',
      'Kotlin',
      'GraphQL',
      'gRPC',
      'Pulumi',
      'Jetpack_Compose',
      'SST',
      'Node',
      'HTML',
      'CSS',
      'SCSS',
      'tailwind',
      'Web_Components',
      'AWS',
      'Github_Actions',
    ],
  },
  {
    path: '~/Jon/Skills',
    input: 'cd ..',
    results: [],
  },
  {
    path: '~/Jon',
    input: 'ls',
    results: ['Skills', 'My_Work'],
  },
  {
    path: '~/Jon',
    input: 'cd My_Work',
    results: [],
  },
  {
    path: '~/Jon/My_Work',
    input: 'ls',
    results: [
      'Center',
      'optimize_health',
      'Inovalon',
      'RBI',
      'Burger_King',
      'Popeyes',
      'Tim_Hortons',
      'CareCloud',
    ],
  },
  {
    path: '~/Jon/My-Work',
    input: 'mkdir ??',
    results: [],
  },
];
